export const DISTRICTS_LIMA = [
  'San Isidro',
  'Miraflores',
  'Surco',
  'San Borja',
  'La Molina',
  'Jesus Maria',
  'Lince',
  'Magdalena del Mar',
  'Pueblo Libre',
  'San Miguel',
  'Magdalena',
  'San Luis',
  'Santa Anita',
  'Ate',
  'Barranco',
  'Breña',
  'Chorrillos',
  'Comas',
  'El Agustino',
  'Independencia',
  'La Victoria',
  'Lima Cercado',
  'Los Olivos',
  'Lurigancho',
  'Lurín',
  'Pachacámac',
  'Puente Piedra',
  'Rímac',
  'San Juan de Lurigancho',
  'San Juan de Miraflores',
  'San Martín de Porres',
  'Santa Rosa',
  'Villa El Salvador',
  'Villa María del Triunfo',
] as const;

export type District = (typeof DISTRICTS_LIMA)[number];
